version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
