version: "3"
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./server/Dockerfile
  #   volumes:
  #     - ./shared:/usr/src/app/shared
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - my-network
  #   env_file: ./server/.env
  #   depends_on:
  #     - redis
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
